# Generated by Django 5.2.1 on 2025-05-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_modelopytorch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('modelo_binario', models.BinaryField()),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ModeloPyTorch',
        ),
    ]
