# Generated by Django 5.2.1 on 2025-05-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_modeloguardado_delete_modelopytorch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloguardado',
            name='modelo_binario',
        ),
        migrations.AddField(
            model_name='modeloguardado',
            name='cov_binario',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='modeloguardado',
            name='mean_binario',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='modeloguardado',
            name='fecha_guardado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
