# Generated by Django 5.2.1 on 2025-05-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_remove_modeloguardado_modelo_binario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloguardado',
            name='modelo_binario',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
